// Constants
export {
  ERR_INCORRECT_LOGIN,
  ERR_LOGIN_FAILED,
  MAX_LENGTH_PASSWORD,
  MAX_LENGTH_PRINCIPAL,
  MIN_LENGTH_PASSWORD,
  MIN_LENGTH_PRINCIPAL,
  MSG_LOGIN_OK,
  PLACEHOLDER_PASSWORD,
  PLACEHOLDER_PRINCIPAL,
  TESTID_PASSWORD_VISIBILITY,
  URL_API_AUTH_LOGIN,
  RPC_GET_EMAIL,
} from './lib/constants';

export type { LoginResponse, LoginPayload } from './lib/dto';
